# Generated by Django 4.1.7 on 2023-04-21 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bms_area_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_area_master_tbl',
            },
        ),
        migrations.CreateModel(
            name='bms_building_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bms_department_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bms_hardware_type_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_hardware_tbl',
            },
        ),
        migrations.CreateModel(
            name='bms_user_area_cards_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('card_name', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('department_id', models.ManyToManyField(to='Device.bms_department_master')),
                ('user_id', models.ManyToManyField(blank=True, to='Authenticate.bms_users')),
            ],
            options={
                'db_table': 'bms_user_area_cards_list_tbl',
            },
        ),
        migrations.CreateModel(
            name='bms_sub_area_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area_name', models.CharField(max_length=100)),
                ('on_image_path', models.CharField(max_length=255)),
                ('off_image_path', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('seating_capacity', models.BigIntegerField()),
                ('devices_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('area_id', models.ManyToManyField(to='Device.bms_area_master')),
                ('department_id', models.ManyToManyField(blank=True, to='Device.bms_department_master')),
            ],
            options={
                'db_table': 'bms_sub_area_master_tbl',
            },
        ),
        migrations.CreateModel(
            name='bms_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.ManyToManyField(blank=True, to='Authenticate.bms_module_master')),
            ],
        ),
        migrations.CreateModel(
            name='bms_locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('N', 'Normal'), ('B', 'Big')], max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_area_id', models.ManyToManyField(blank=True, to='Device.bms_sub_area_master')),
            ],
        ),
        migrations.CreateModel(
            name='bms_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Newuser'), ('V', 'Visitor'), ('A', 'Access'), ('C', 'Conference')], max_length=100)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ManyToManyField(blank=True, to='Authenticate.bms_users')),
            ],
        ),
        migrations.CreateModel(
            name='bms_floor_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tower_id', models.ManyToManyField(related_name='de', to='Device.bms_building_master')),
            ],
        ),
        migrations.CreateModel(
            name='bms_device_type_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_type_id', models.ManyToManyField(to='Device.bms_hardware_type_master')),
            ],
            options={
                'db_table': 'bms_device_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_device_status_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('device_id', models.ManyToManyField(related_name='device_id', to='Device.bms_sub_area_master')),
            ],
            options={
                'db_table': 'bms_device_status_tbl',
            },
        ),
        migrations.CreateModel(
            name='bms_device_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_informations', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_user', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=23)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_details_date', models.DateTimeField(auto_now=True)),
                ('device_type', models.ManyToManyField(to='Device.bms_device_type_master')),
                ('devices_details', models.ManyToManyField(blank=True, to='Device.bms_sub_area_master')),
            ],
            options={
                'db_table': 'bms_device_master_tbl',
            },
        ),
        migrations.AddField(
            model_name='bms_department_master',
            name='floor_id',
            field=models.ManyToManyField(blank=True, to='Device.bms_floor_master'),
        ),
        migrations.AddField(
            model_name='bms_area_master',
            name='floor_id',
            field=models.ManyToManyField(blank=True, to='Device.bms_floor_master'),
        ),
        migrations.CreateModel(
            name='bms_access_control_rfid_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_no', models.IntegerField()),
                ('card_type', models.CharField(choices=[('N', 'No-assign'), ('S', 'Static'), ('D', 'Dynamic')], max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=100)),
                ('access_start_time', models.DateField(default=django.utils.timezone.now)),
                ('access_end_time', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('access_area_id', models.ManyToManyField(blank=True, to='Device.bms_sub_area_master')),
                ('user_id', models.ManyToManyField(to='Authenticate.bms_users')),
            ],
        ),
    ]
