# Generated by Django 4.1.7 on 2023-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bms_inventory_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'In-Active')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=300)),
                ('item_image', models.ImageField(upload_to='uploads/')),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('stock_quantity', models.FloatField()),
                ('minimum_quantity', models.IntegerField(default=5)),
                ('order_from', models.CharField(choices=[('M', 'Manual'), ('A', 'Amazon'), ('F', 'Flipkart')], max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'In-Active')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ManyToManyField(related_name='items', to='Inventory.bms_inventory_category')),
            ],
            options={
                'db_table': 'item_details_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_manage_inventory_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('stock_quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('total', models.FloatField(editable=False)),
                ('grand_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ManyToManyField(related_name='manage_stock', to='Inventory.bms_item_details')),
            ],
            options={
                'db_table': 'manage_inventory_tbl',
            },
        ),
    ]
