# Generated by Django 4.1.7 on 2023-04-21 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bms_Module_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=254)),
                ('module_slug', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'In-Active')], max_length=100)),
                ('created_module_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_module_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_module_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('created_role_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_role_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_role_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_User_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user_type_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bms_user_type_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('created_user_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_user_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_Users_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('phone_no', models.CharField(max_length=16)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=2321)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'In-Active')], max_length=100)),
                ('created_user_details_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_details_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_user_details_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_Users_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_no', models.CharField(max_length=16)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=2321)),
                ('created_user_details_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_details_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_user_register_tbl',
            },
        ),
        migrations.CreateModel(
            name='Bms_Userss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('created_user_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_date', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bms_roles')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bms_users_details')),
            ],
            options={
                'db_table': 'bms_userss_tbl',
            },
        ),
    ]
