# Generated by Django 4.1.7 on 2023-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0001_initial'),
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_users_register',
            name='department_id',
            field=models.ManyToManyField(to='Device.bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_register',
            name='locker_id',
            field=models.ManyToManyField(to='Device.bms_locker'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='department_id',
            field=models.ManyToManyField(related_name='dep', to='Device.bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='locker_id',
            field=models.ManyToManyField(related_name='locker', to='Device.bms_locker'),
        ),
        migrations.AddField(
            model_name='bms_users',
            name='role_id',
            field=models.ManyToManyField(blank=True, related_name='song', to='Authenticate.bms_roles'),
        ),
        migrations.AddField(
            model_name='bms_users',
            name='user_details',
            field=models.ManyToManyField(related_name='abc', to='Authenticate.bms_users_details'),
        ),
        migrations.AddField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, related_name='aaa', to='Authenticate.bms_roles'),
        ),
        migrations.AddField(
            model_name='bms_roles',
            name='permissions_id',
            field=models.ManyToManyField(related_name='dev', to='Authenticate.bms_module_master'),
        ),
    ]
