# Generated by Django 4.1.7 on 2023-04-21 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bms_visiter_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=23)),
                ('last_name', models.CharField(max_length=23)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=233)),
                ('created_module_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_module_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ManyToManyField(to='Authenticate.bms_users')),
            ],
            options={
                'db_table': 'bms_visiter_details',
            },
        ),
        migrations.CreateModel(
            name='Bms_visitor_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_person', models.CharField(max_length=23)),
                ('department_name', models.CharField(max_length=23)),
                ('meeting_time', models.TimeField(max_length=32)),
                ('meeting_purpose', models.CharField(max_length=23)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('out_remark', models.CharField(max_length=12)),
                ('rfid_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('In_progress', 'In_progress'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], max_length=23)),
                ('access_from_time', models.TimeField()),
                ('access_to_time', models.TimeField()),
                ('access_area', models.TextField()),
                ('locker_id', models.TextField()),
                ('created_module_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_module_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ManyToManyField(to='Visitor.bms_visiter_details')),
            ],
            options={
                'db_table': 'Bms_visitor_activity',
            },
        ),
    ]
